from __future__ import annotations


class Appendix:
    """Static handbook tables and glossary snippets used in prompts."""

    Wegezeiten_Wegesachkosten = (
        "### Anhang 5: Wegezeiten und -sachkosten\n\n"
        "Wegezeiten umfassen den Zeitaufwand des Normadressaten, um von seinem Wohnort bzw. "
        "Sitz zur zuständigen Behörde zu gelangen. Die Wegesachkosten beschreiben den "
        "Sachaufwand, um diesen Weg zurückzulegen und beinhalten beispielsweise Fahrkarten "
        "für den ÖPNV oder Kraftstoff für das eigene Fahrzeug.\n\n"
        "Wegezeiten und Wegesachkosten werden bei der Ermittlung des Erfüllungsaufwands "
        "berücksichtigt, wenn die jeweilige Regelung ein persönliches Erscheinen in einer "
        "Behörde oder Stelle vorschreibt und keine Alternativen wie den Postweg oder "
        "Online-Verfahren erlaubt. "
        "Gleiches gilt, wenn Behördenvertreterinnen und -vertreter verpflichtet sind, "
        "beispielsweise im Rahmen von Gremiensitzungen persönlich andere Ämter oder "
        "Stellen aufzusuchen.\n\n"
        "Die folgende Tabelle zeigt pauschale Wegezeiten und -sachkosten in Abhängigkeit "
        "der zuständigen Verwaltungsebene. Gibt es belastbare Anhaltspunkte dafür, dass "
        "der nach der Tabelle ermittelte Wert aller Wahrscheinlichkeit nach über- oder "
        "unterzeichnet ist, sollte der aus Fachsicht realistischere Wert für die "
        "Ermittlung genutzt werden.\n\n"
        "*Wegezeiten und -sachkosten nach Verwaltungsebene*\n\n"
        "| Verwaltungsebene | Wegezeiten (Min.) | Wegesachkosten (Euro) |\n"
        "| --- | --- | --- |\n"
        "| Gemeinde | 15 | 1,10 |\n"
        "| Kreis | 22 | 3,10 |\n"
        "| Regierungsbezirk/Land | 59 | 13,20 |\n"
        "| Durchschnitt | 20 | 2,60 |\n"
    )
    Zeitwerttabelle_Verwaltung = (
        "### Anhang 7: Zeitwerttabelle Verwaltung\n\n"
        "Liegen noch keine vergleichbaren Daten für den Zeitaufwand einzelner Tätigkeiten "
        "vor, kann auf die sogenannte Zeitwerttabelle Verwaltung zurückgegriffen werden. "
        "Die Zeitwerttabelle weist für einen großen Teil der auf Seite 46 angegebenen "
        "Standardaktivitäten Minutenwerte aus. Die Standardaktivitäten sind nach dem Grad "
        "der Schwierigkeit in einfach, mittel und hoch gestaffelt.\n\n"
        "Der nach der Zeitwerttabelle ermittelte Zeitwert (das heißt der Zeitaufwand für "
        "eine Tätigkeit) sollte immer anhand begründbarer Einschätzungen aus fachlicher "
        "Sicht überprüft werden. Gibt es belastbare Anhaltspunkte dafür, dass der nach der "
        "Tabelle ermittelte Wert aller Wahrscheinlichkeit nach zu hoch oder zu niedrig "
        "angesetzt ist, sollte der aus Fachsicht realistischere Wert für die Ermittlung "
        "genutzt werden.\n\n"
        "*Zeitwerttabelle Verwaltung*\n\n"
        "| Nr. | Standardaktivität | Einfache Komplexität (Min.) | Mittlere Komplexität (Min.) | Hohe Komplexität (Min.) | Erläuterung |\n"
        "| --- | --- | --- | --- | --- | --- |\n"
        "| 1 | Einarbeiten in die Vorgabe | 2 | 13 | 413 | Welcher Aufwand entsteht regelmäßig, um sich mit der gesetzlichen Verpflichtung vertraut zu machen? |\n"
        "| 2 | Beraten, Vorgespräche führen | 3 | 30 | 460 (1 PT) | Welcher Aufwand fällt zur Beantwortung von Fragen durch Bürgerinnen und Bürger oder Unternehmen und der Klärung von Sachverhalten an? |\n"
        "| 3 | Formelle Prüfung, Daten sichten | 5 | 30 | 110 | Welcher Aufwand entsteht durch Kontrolle auf Vollständigkeit und Richtigkeit von vorhandenen Informationen wie z. B. Nachweisen? |\n"
        "| 4 | Eingang bestätigen oder Einholen fehlender Daten | 5 | 10 | 22 | Welcher Aufwand entsteht durch Eingangsbestätigungen oder die Nachforderung fehlender Daten? |\n"
        "| 5 | Inhaltliche Prüfung, Daten erfassen | 8 | 60 | 480 (1 PT) | Welcher Aufwand fällt durch die Prüfung von Formularen, Belegen und Berechnungen sowie durch das elektronische Erfassen an? |\n"
        "| 6 | Berechnungen durchführen | 9 | 120 | X[^7] | Welcher Aufwand fällt für Berechnungen, Bewertungen und Zählungen an? |\n"
        "| 7 | Ergebnisse/Berechnungen überprüfen und ggf. korrigieren | 4 | 30 | 1 170 (3,7 PT) | Welcher Aufwand entsteht durch die Prüfung von Ergebnissen z. B. durch das Vieraugenprinzip oder Mitzeichnungen? |\n"
        "| 8 | Interne Sitzungen | 2 | 60 | 2 120 (4,4 PT) | Welcher Aufwand entsteht durch notwendige interne Sitzungen? |\n"
        "| 9 | Externe Sitzungen | 5 | 80 | 2 640 (5,5 PT) | Welcher Aufwand entsteht durch notwendige externe Sitzungen z. B. mit externen Sachverständigen oder anderen Behörden? |\n"
        "| 10 | Daten übermitteln oder veröffentlichen | 1 | 10 | 60 | Welcher Aufwand fällt an, um Informationen zu veröffentlichen oder an andere öffentliche Stellen weiterzugeben? |\n"
        "| 11 | Abschließende Informationen aufbereiten, Bescheid erstellen | 5 | 60 | 480 (1 PT) | Welcher Aufwand entsteht z. B. durch das Erstellen von Bescheiden oder Vermerken? |\n"
        "| 12 | Zahlungen anweisen, annehmen oder überwachen | 1 | 5 | 18 | Welcher Aufwand fällt für Überweisungen oder die Prüfung von Zahlungsein- und -ausgängen an? |\n"
        "| 13 | Korrektur bzw. weitere Informationen bei Rückfragen vorlegen | 30 | 60 | 120 | Welcher Aufwand entsteht durch Rückfragen nach Bescheiderhalt und ggf. Fehlerkorrekturen? |\n"
        "| 14 | Kopieren, archivieren, verteilen | 2 | 10 | 20 | Welcher Aufwand entsteht durch Kopier- oder Archivierungstätigkeiten und das Verteilen von Informationen innerhalb der Behörde? |\n"
        "| 15 | Fortbildungen und Schulungen | 1 | 3 | 2 640 (5,5 PT) | Welcher Aufwand entsteht dadurch, dass die Erfüllung einer Vorgabe eine Schulung voraussetzt? |\n"
        "| 16 | Überwachungs- und Aufsichtsmaßnahmen | 8 | 156 | 25 000 (52,1 PT) | Welcher Aufwand fällt durch Begehungen in Betrieben oder Besuchen bei Bürgerinnen und Bürgern an? |\n"
        "| 17 | Anpassen von internen Prozessen | 12 | 4 080 (8,5 PT) | 67 200 (140 PT) | Welcher Aufwand entsteht, wenn interne Prozesse verändert oder angepasst werden müssen? |\n\n"
        "[^7]: Aufgrund methodischer Unterschiede wurde hier auf die Darstellung von „hoch“ verzichtet.\n\n"
        "PT: Persontag(e)\n"
        "Stand: Januar 2025; Quelle: StBA\n"
    )
    Lohnkostentabelle_Verwaltung = (
        "### Anhang 8: Lohnkostentabelle Verwaltung\n\n"
        "In Anlehnung an die Lohnkostentabelle für Informationspflichten der Wirtschaft "
        "nach dem Standardkosten-Modell wurde für die Verwaltung vom StBA eine eigene "
        "Tariflohntabelle entwickelt. Analog zum Bereich Wirtschaft werden die "
        "Standardlohnsätze der Verwaltung getrennt nach Hierarchieebene und "
        "Qualifikationsniveau in Euro ausgewiesen.\n\n"
        "*Lohnkosten pro Stunde in Euro*\n\n"
        "| Verwaltungsebene | Einfacher und mittlerer Dienst | Gehobener Dienst | Höherer Dienst | Durchschnitt |\n"
        "| --- | --- | --- | --- | --- |\n"
        "| Bund | 33,80 | 40,40 | 67,60 | 44,40 |\n"
        "| Länder | 30,50 | 43,20 | 69,30 | 46,70 |\n"
        "| Kommunen | 25,50 | 42,20 | 70,40 | 40,70 |\n"
        "| Sozialversicherung | 30,30 | 46,30 | 73,20 | 48,10 |\n"
        "| Durchschnitt Öffentliche Verwaltung, Verteidigung, Sozialversicherung | 27,30 | 42,90 | 69,30 | 44,40 |\n\n"
        "Stand: 2025; Quelle: StBA\n\n"
        "*Lohnkosten pro Mitarbeiterkapazität (MAK) in Euro*\n\n"
        "| Verwaltungsebene | Einfacher und mittlerer Dienst | Gehobener Dienst | Höherer Dienst | Durchschnitt |\n"
        "| --- | --- | --- | --- | --- |\n"
        "| Bund | 54 080 | 64 640 | 108 160 | 71 040 |\n"
        "| Länder | 48 800 | 69 120 | 110 880 | 74 720 |\n"
        "| Kommunen | 40 800 | 67 520 | 112 640 | 65 120 |\n"
        "| Sozialversicherung | 48 480 | 74 080 | 117 120 | 76 960 |\n"
        "| Durchschnitt Öffentliche Verwaltung, Verteidigung, Sozialversicherung | 43 680 | 68 640 | 110 880 | 71 040 |\n\n"
        "Stand: 2025; Quelle: StBA\n"
        "1 MAK = 1 Personenjahr à 200 Arbeitstage mit je 8 Stunden\n"
    )
    Zeitwerttabelle_Wirtschaft = (
        "### Anhang: Zeitwerttabelle Wirtschaft\n\n"
        "*Zeitwerttabelle Wirtschaft fuer Informationspflichten*\n\n"
        "| Nr. | Standardaktivitaet | Einfach (Min.) | Mittel (Min.) | Hoch (Min.) | Erlaeuterung |\n"
        "| --- | --- | --- | --- | --- | --- |\n"
        "| 1 | Einarbeitung in die Informationspflicht | 3 | 5 | 60 | Welcher Aufwand entsteht regelmaessig, um sich mit der gesetzlichen Verpflichtung vertraut zu machen? |\n"
        "| 2 | Beschaffung von Daten | 2 | 10 | 120 | Welcher Aufwand faellt durch die Beschaffung notwendiger Informationen und Daten an? |\n"
        "| 3 | Formulare ausfuellen, Beschriftung, Kennzeichnung | 3 | 5 | 30 | Welcher Aufwand entsteht z. B. durch das Ausfuellen eines Antragsformulars? |\n"
        "| 4 | Berechnungen durchfuehren | 2 | 20 | 240 | Welche Berechnungen, Bewertungen, Zaehlungen muessen durchgefuehrt werden? |\n"
        "| 5 | Ueberpruefung der Daten und Eingaben | 1 | 10 | 60 | Entsteht Aufwand durch Kontrollmassnahmen? |\n"
        "| 6 | Fehlerkorrektur | 2 | 10 | 60 | Entsteht Aufwand durch Korrekturmassnahmen? |\n"
        "| 7 | Aufbereitung der Daten | 3 | 20 | 300 | Welcher Aufwand entsteht durch die Aufbereitung von Daten? |\n"
        "| 8 | Datenuebermittlung und Veroeffentlichung | 1 | 2 | 5 | Welcher Aufwand entsteht durch die Datenuebermittlung und/oder Veroeffentlichung von Daten oder Informationen? |\n"
        "| 9 | Interne Sitzungen | 5 | 60 | 600 (1,3 PT) | Welcher Aufwand entsteht durch notwendige interne Sitzungen? |\n"
        "| 10 | Externe Sitzungen | 10 | 60 | 480 (1 PT) | Welcher Aufwand entsteht durch notwendige externe Sitzungen (z. B. mit Steuerberatung)? |\n"
        "| 11 | Ausfuehren von Zahlungsanweisungen | 2 | 4 | 15 | Entsteht Aufwand z. B. durch die Veranlassung einer Online-Ueberweisung? |\n"
        "| 12 | Kopieren, Archivieren, Verteilen | 1 | 2 | 12 | Entsteht Aufwand z. B. durch Kopiertaetigkeiten oder Archivierungsarbeiten? |\n"
        "| 13 | Pruefung durch oeffentliche Stellen | 5 | 50 | 480 (1 PT) | Welcher Aufwand wird z. B. durch die Betriebspruefung ausgeloest? |\n"
        "| 14 | Korrekturen, die aufgrund von Pruefungen durchgefuehrt werden muessen | 4 | 30 | 500 (1 PT) | Entsteht Aufwand durch Korrekturen und eine Ueberarbeitung der Daten? |\n"
        "| 15 | Weitere Informationsbeschaffung | 3 | 15 | 120 | Entsteht Aufwand durch zusaetzliche Informationsbereitstellung? |\n"
        "| 16 | Fortbildungs- und Schulungsteilnahmen | 2 | 33 | 600 (1,3 PT) | Entsteht Aufwand dadurch, dass die Erfuellung einer Informationspflicht eine Schulung voraussetzt? |\n"
        "| 17 | Anpassen von internen Prozessen | 300 | 720 (1,5 PT) | 3 480 (7,3 PT) | Welcher Aufwand entsteht, wenn interne Prozesse veraendert oder angepasst werden muessen? |\n"
        "| 18 | Ueberwachungsmassnahmen | 30 | 240 | 4 200 (8,8 PT) | Entsteht Aufwand durch das Mitwirken bei Ueberwachungsmassnahmen z. B. durch Behoerden wie die Bafin? |\n"
        "| 19 | Beschaffen von Dienstleistungen | 10 | 60 | 300 | Entsteht Zeitaufwand fuer die Beschaffung von externen Dienstleistungen wie z. B. fuer Gutachten oder Abnahmen? |\n"
    )
    Zeitwerttabelle_Buerger = (
        "### Anhang 3: Zeitwerttabelle Buergerinnen und Buerger\n\n"
        "| Nr. | Standardaktivitaet | Einfach (Min.) | Mittel (Min.) | Hoch (Min.) |\n"
        "| --- | --- | --- | --- | --- |\n"
        "| 1 | Sich mit der gesetzlichen Verpflichtung vertraut machen | 2 | 5 | 15 |\n"
        "| 2 | Fachliche Beratung in Anspruch nehmen | 5 | 20 | 64 |\n"
        "| 3 | Informationen oder Daten sammeln und zusammenstellen | 2 | 3 | 25 |\n"
        "| 4 | Informationen oder Daten aufbereiten | 1 | 30 | 480 |\n"
        "| 5 | Formulare ausfuellen | 3 | 6 | 60 |\n"
        "| 6 | Schriftstuecke aufsetzen | 3 | 5 | 10 |\n"
        "| 7 | Informationen oder Daten an die zustaendigen Stellen uebermitteln | 1 | 2 | 5 |\n"
        "| 8 | Zahlungsanweisungen ausfuehren | 1 | 2 | 3 |\n"
        "| 9 | Unterlagen kopieren, abheften, abspeichern | 1 | 3 | 4 |\n"
        "| 10 | Pruefung durch oeffentliche Stellen durchfuehren lassen | 3 | 26 | 140 |\n"
        "| 11 | Weitere Informationen bei Rueckfragen vorlegen | 2 | 5 | 15 |\n"
    )
    Lohnkostentabelle_Wirtschaft = (
        "### Anhang: Lohnkostentabelle Wirtschaft\n\n"
        "*Lohnkosten pro Stunde in Euro*\n\n"
        "| Wirtschaftsabschnitt | Niedrig | Mittel | Hoch | Durchschnitt |\n"
        "| --- | --- | --- | --- | --- |\n"
        "| A Land- und Forstwirtschaft, Fischerei | 22,70 | 25,60 | 45,80 | 25,00 |\n"
        "| B Bergbau und Gewinnung von Steinen und Erden | 32,60 | 41,80 | 85,60 | 45,00 |\n"
        "| C Verarbeitendes Gewerbe | 31,60 | 44,20 | 76,20 | 46,20 |\n"
        "| D Energieversorgung | 33,60 | 54,90 | 80,70 | 57,80 |\n"
        "| E Wasserversorgung; Abwasser- und Abfallentsorgung und Beseitigung von Umweltverschmutzungen | 28,50 | 37,00 | 64,70 | 37,40 |\n"
        "| F Baugewerbe | 26,10 | 33,70 | 59,50 | 33,70 |\n"
        "| G Handel; Instandhaltung und Reparatur von Kraftfahrzeugen | 23,60 | 32,40 | 62,40 | 33,40 |\n"
        "| H Verkehr und Lagerei | 25,90 | 32,20 | 62,80 | 32,10 |\n"
        "| I Gastgewerbe | 21,70 | 24,40 | 39,70 | 23,60 |\n"
        "| J Information und Kommunikation | 25,10 | 49,90 | 63,70 | 52,80 |\n"
        "| K Erbringung von Finanz- und Versicherungsdienstleistungen | 29,00 | 54,40 | 93,10 | 57,90 |\n"
        "| L Grundstuecks- und Wohnungswesen | 24,10 | 34,70 | 56,20 | 35,00 |\n"
        "| M Erbringung von freiberuflichen, wissenschaftlichen und technischen Dienstleistungen | 25,50 | 40,90 | 64,20 | 46,70 |\n"
        "| N Erbringung von sonstigen wirtschaftlichen Dienstleistungen | 23,30 | 30,20 | 55,00 | 28,00 |\n"
        "| P Erziehung und Unterricht | 26,30 | 36,40 | 53,10 | 43,20 |\n"
        "| Q Gesundheits- und Sozialwesen | 27,00 | 34,20 | 62,00 | 36,90 |\n"
        "| R Kunst, Unterhaltung und Erholung | 22,90 | 32,20 | 51,00 | 31,70 |\n"
        "| S Erbringung von sonstigen Dienstleistungen | 23,60 | 30,30 | 49,00 | 32,10 |\n"
        "| Gesamtwirtschaft (A-S ohne O) | 26,10 | 37,10 | 62,40 | 38,60 |\n"
    )
    Begriffsdefinitionen_Erlaeuterungen = {
        "erfuellungsaufwand": (
            "Der Erfüllungsaufwand umfasst den gesamten messbaren Zeitaufwand und die Kosten, "
            "die durch die Befolgung einer bundesrechtlichen Vorschrift bei Bürgerinnen und "
            "Bürgern, Wirtschaft sowie der öffentlichen Verwaltung entstehen. Teil des "
            "Erfüllungsaufwands sind Bürokratiekosten, die durch die Erfüllung von "
            "Informationspflichten verursacht werden. Diese sind beim Normadressaten Wirtschaft "
            "gesondert auszuweisen.\n\n"
            "Bei Bürgerinnen und Bürgern sowie der Verwaltung ist eine Unterscheidung zwischen "
            "Informationspflichten und anderen Vorgaben entbehrlich.\n\n"
            "Zum Erfüllungsaufwand der Verwaltung gehört der Vollzugsaufwand. Auch das "
            "fiskalische Handeln der Verwaltung als Normadressat (z. B. als Halter von Kfz oder "
            "als Bauherr) ist dem Erfüllungsaufwand zuzurechnen. Erfüllungsaufwand entsteht der "
            "Verwaltung insbesondere durch die Bearbeitung von Anträgen oder durch "
            "Überwachungsaufgaben sowie durch die Bereitstellung von Informationen und "
            "Materialien (z. B. Antragsformulare) für Bürgerinnen und Bürger oder für die "
            "Wirtschaft oder für andere Teile der Verwaltung.\n\n"
            "Einnahmen und Ausgaben, die bei Gesetzentwürfen unter Buchstabe D des Vorblattes "
            "ausgewiesen werden, bleiben beim Erfüllungsaufwand unberücksichtigt (z. B. "
            "Steuermehr-/ -mindereinnahmen, Aufwendungen gem. Artikel 104a Absatz3 und 4 GG).\n\n"
            "Beim Erfüllungsaufwand wird lediglich die Kostenseite betrachtet. Es findet keine "
            "Saldierung mit dem Nutzen einer Regelung statt.\n"
        ),
        "normadressaten": (
            "Bürgerinnen und Bürger, Wirtschaft sowie die öffentliche Verwaltung stellen die "
            "möglichen Normadressaten dar.\n\n"
            "Zum Normadressaten Wirtschaft zählt jede Einheit, die eine wirtschaftliche Tätigkeit "
            "ausübt, die zum Bruttoinlandsprodukt beiträgt und dem Privatsektor zugerechnet wird. "
            "Der Privatsektor umfasst auch karitative Organisationen und den ehrenamtlichen "
            "Sektor; nicht darunter fallen öffentliche Verwaltung, private Haushalte und "
            "exterritoriale Körperschaften und Organisationen.\n\n"
            "Als öffentliche Verwaltung gelten die mit der Wahrnehmung von Verwaltungsaufgaben "
            "betrauten Verwaltungsträger (rechtsfähige Körperschaften, Anstalten und Stiftungen "
            "des öffentlichen Rechts einschließlich Beliehene im Rahmen der ihnen übertragenen "
            "hoheitlichen Kompetenzen).\n\n"
            "Alle Vorgaben, die sich an natürliche Personen richten, sind Vorgaben für "
            "Bürgerinnen und Bürger. Führt eine natürliche Person ein Unternehmen, dann zählen "
            "diejenigen Vorgaben, die sich an die Person aufgrund ihrer Eigenschaft als "
            "Unternehmerinnen und Unternehmer richten, als Vorgaben für die Wirtschaft.\n\n"
            "Vorgaben können mehrere Normadressaten gleichzeitig betreffen.\n"
        ),
        "prozess": (
            "Mehrere Vorgaben, die in der Praxis in einem Zusammenhang erfüllt werden, können "
            "zu einem Prozess gebündelt werden.\n"
        ),
        "regelungsvorhaben": (
            "Bei Regelungsvorhaben handelt es sich um alle Entwürfe von Rechts- und "
            "Verwaltungsvorschriften, die nach den §§ 43, 44, 62 Absatz 2 und § 70 Absatz 1 der "
            "GGO mit einer Gesetzesfolgenabschätzung zu versehen sind.\n"
        ),
        "vorgaben": (
            "Vorgaben sind Einzelregelungen, die bei den Normadressaten unmittelbar zur Änderung "
            "von Kosten, Zeitaufwand oder beidem führen. Sie ergeben sich aus bundesrechtlichen "
            "Regelungen. Sie veranlassen die Normadressaten, bestimmte Ziele oder Anordnungen zu "
            "erfüllen oder auch bestimmte Handlungen zu unterlassen. Dazu zählen auch "
            "Verpflichtungen zur Kooperation mit Dritten sowie zur Überwachung und Kontrolle "
            "von Zuständen, Handlungen, numerischen Werten oder Verhaltensweisen. "
            "Informationspflichten bilden eine Teilmenge der Vorgaben.\n\n"
            "„Unmittelbar“ bedeutet hierbei, dass die Änderung von Kosten oder Zeitaufwand in "
            "direkter Verbindung mit der Befolgung der jeweiligen Vorgabe steht. Ein Merkmal "
            "von Vorgaben ist, dass Bürgerinnen und Bürger, Wirtschaft sowie öffentliche "
            "Verwaltung ihnen Folge leisten müssen, um nicht gegen Rechtsvorschriften zu "
            "verstoßen oder etwaige Ansprüche auf staatliche Leistungen zu verlieren "
            "(z. B. Anträge).\n\n"
            "Bei der Identifizierung von Vorgaben ist zu beachten, dass der Gesetzgeber zum "
            "Teil neben Ge- oder Verboten lediglich Ziele oder Grenzwerte festgelegt oder "
            "z. B. durch staatliche Förderungen Verhaltensänderungen erreichen will. Auch "
            "solche Einzelregelungen sind als Vorgaben zu verstehen, weil sie unmittelbar zur "
            "Änderung von Kosten bzw. Zeitaufwand bei den Normadressaten führen.\n"
        ),
    }
